### ISSUE TITLE
Add option to allow customer to update a field in his custom fields

### ISSUE THREAD

**Issue by bastienmothais** [bastienmothais/sharpeye#2]
Sometimes customer could update a field in his custom field from an email. For example, if we send an email to the customer to ask him "on what time do you prefer receive our email?" customer should be able to click in a link to go to a new page in order to select an hour.

**Comment by dansackett** [comment]
This feature was discussed a while ago but was never implemented. The idea would be like the questionnaire and subscription forms but it would be an implicit update form. This is a nice enhancement for the future.

**Comment by bastienmothais** [comment]
We are agree, it is a nice enhancement. For this reason, it could be great if we can use it as soon as possible :)

From Barcelona we need this development to send our product in several countries. Please, add this on your road map and let me know its position.

i remain at your disposal should you have any questions concerning this matter.

Thank you.

**Comment by dansackett** [comment]
For the sake of conversation history, this is something we would like to implement but likely will not be able to until April when we have more flexibility with the feature schedule.

**Comment by bastienmothais** [comment]
Duplicate issue, I close this one and I leave opened the main issue: https://github.com/EonianTechnology/SharpEye/issues/136
